image: dchevell/docker-release-maker:latest
clone:
  depth: full

pipelines:
  custom:
    create-release-base-4:
      - step:
          script:
            - git remote set-url origin ${BITBUCKET_GIT_HTTP_ORIGIN}
            - git fetch --all
            - export BASE_BRANCH='base-4'
            - export MAC_PRODUCT_KEY='fisheye'
            - export DOCKERFILE_VERSION_STRING='FECRU_VERSION'
            - export DEFAULT_RELEASE='true'
            - export ADDITIONAL_TAG_SUFFIXES='alpine'
            - python /usr/src/app/run.py --create
  branches:
    base-4:
      - step:
          script:
            - git remote set-url origin ${BITBUCKET_GIT_HTTP_ORIGIN}
            - git fetch --all
            - export BASE_BRANCH='base-4'
            - export MAC_PRODUCT_KEY='fisheye'
            - export DOCKERFILE_VERSION_STRING='FECRU_VERSION'
            - export DEFAULT_RELEASE='true'
            - export ADDITIONAL_TAG_SUFFIXES='alpine'
            - python /usr/src/app/run.py --update